TRAJECTORY_PATH: "Data/Arpette/trajectory.txt"

MNT_PATH: "Data/espg2056_raster.tif"

OUTPUT_DIR: "Output/Arpette"

LAS_DIR: "Data/Arpette/ARPETTE_LV95_HELL_1560II_CH1_211020_{flight_id}.laz"

LOG_DIR: "Data/Arpette/timestamps/211020_{flight_id}_Channel_1.sdc.log"



