#------------------- ALS Vallet 2020 config -------------------#

# Input files / directories
TRAJECTORY_PATH: "Data/Vallet2020/Vallet2020_CH1903.txt"
DTM_PATH: "Data/epsg2056_raster.tif"
OUTPUT_DIR: "Output/Vallet/test_1"
LAS_DIR: "Data/Vallet2020/ALS_line{flight_id}.txt"
LOG_DIR: "Data/Vallet2020/GPS_Times.json"

# Parameters
DAY_OF_WEEK: 0
TRAJECTORY_COLUMNS: ["gps_time", "lon", "lat", "alt", "roll", "pitch", "yaw"]

# DTM
RASTER_BUFFER: 250 # Buffer for the raster generation around the min/max North/East position of the trajectories [m]


# Lidar scanning mode 
LIDAR_SCAN_MODE: "across" # Options: "across", "left", "right" 
LIDAR_TILT_ANGLE: 0       # [deg]: "Vallet"-> 0, "Arpette"-> 14
LIDAR_FOV: 75             # [deg]: "Vallet"-> 75, "Arpette"-> 60

# Patch generation  
PAIR_MODE: "successive" # Options: "successive", "all". Successive: only generate patches from successive lines. All: generate patches from all lines.
PATCH_DIMS: [100, 150, 400] # [length, width, height] [m]

# Footprint
FLIGHT_DOWNSAMPLING: 100 # Take a flight position every 10 coordinates in the trajectory file

# Extraction
EXTRACTION_MODE: "binary" # Options: "binary", "Extra_Bytes", "independent". independent: extract all patches independently. Extra_Bytes: write extra bytes in the .laz 
