GPSTIME_PATH: "Config/GPSTime_config.json"

FLIGHT_PATH: "Data/Vallet2020_CH1903.txt"

MNT_PATH: "Data/espg2056_raster.tif"

OUTPUT_DIRECTORY: "UI_patch2"

LAS_PATTERN: "Data/ALS{flight}_baseline.las"


