#------------------- ALS Vallet 2020 config -------------------#

# Input files / directories
TRAJECTORY_PATH: "Data/Vallet2020/Vallet2020_CH1903.txt"
MNT_PATH: "Data/espg2056_raster.tif"
OUTPUT_DIR: "Output/Vallet/w150_l100_s400"
LAS_DIR: "Data/Vallet2020/ALS_line{flight_id}.txt"
LOG_DIR: "Data/Vallet2020/GPS_Times.json"

# Parameters
DATASET_NAME: "Vallet" # Options: "Arpette", "Vallet"

# Lidar scanning mode 
LIDAR_SCAN_MODE: "across" # Options: "across", "left", "right" 
LIDAR_TILT_ANGLE: 0       # [deg]: "Vallet"-> 0, "Arpette"-> 14
LIDAR_FOV: 75             # [deg]: "Vallet"-> 75, "Arpette"-> 60

# Patch generation  
PAIR_MODE: "successive" # Options: "successive", "all". Successive: only generate patches from successive lines. All: generate patches from all lines.

# Footprint
FLIGHT_SAMPLING: 10 # Take a flight position every 10 coordinates 