#------------------- ALS Vallet 2020 config -------------------#

# Input files / directories
TRAJECTORY_PATH: "Data/Vallet2020/Vallet2020_CH1903.txt"
MNT_PATH: "Data/espg2056_raster.tif"
OUTPUT_DIR: "Output/Vallet/test_1"
LAS_DIR: "Data/Vallet2020/ALS_line{flight_id}.txt"
LOG_DIR: "Data/Vallet2020/GPS_Times.json"

# Parameters
DATASET_NAME: "Vallet" # Options: "Arpette", "Vallet"

# Lidar scanning mode 
LIDAR_SCAN_MODE: "across" # Options: "across", "left", "right" 
LIDAR_TILT_ANGLE: 0       # [deg]: "Vallet"-> 0, "Arpette"-> 14
LIDAR_FOV: 75             # [deg]: "Vallet"-> 75, "Arpette"-> 60

# Patch generation  
PAIR_MODE: "successive" # Options: "successive", "all". Successive: only generate patches from successive lines. All: generate patches from all lines.
PATCH_DIMS: [100, 150, 400] # [length, width, height] [m]

# Footprint
FLIGHT_SAMPLING: 10 # Take a flight position every 10 coordinates in the trajectory file
POSITION_BUFFER: 12.5 # the projected forward and backward distance from the flight position to consider for the footprint

# Extraction
EXTRACTION_MODE: "encoded" # Options: "encoded", "independent". independent: extract all patches independently. encoded: outputs single file with classification code 